dist: bionic
before_script:
  - export TARGET_OS=bionic
  - mkdir /tmp/hrim
  - mv * /tmp/hrim
  - sudo apt-get update
  - sudo apt-get install curl
  - curl http://repo.ros2.org/repos.key | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main $TARGET_OS main" > /etc/apt/sources.list.d/ros2-latest.list'
  - sudo apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sudo apt-get update
  - sudo apt-get install build-essential git python3-colcon-common-extensions python3-pip python-rosdep python3-vcstool wget
  - sudo -H python3 -m pip install -U argcomplete flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pytest-repeat pytest-rerunfailures
  - sudo -H python3 -m pip install -U pytest pytest-cov pytest-runner setuptools
  - sudo -H python3 -m pip install -U lxml
  - sudo apt-get install libasio-dev libtinyxml2-dev grep
  - mkdir -p ~/ros2_ws/src
  - export ROS_DISTRO=crystal
  - sudo apt-get install ros-$ROS_DISTRO-*
  - cp -R /tmp/hrim /home/travis/ros2_ws/src/hrim
  - python3 /tmp/hrim/hrim.py generate --platform ros2 all
  - cp -R /tmp/hrim/generated /home/travis/ros2_ws/src/hrim
script:
  - cd ~/ros2_ws/
  - source /opt/ros/ardent/setup.bash
  - colcon build --symlink-install --merge-install
