sudo: required
dist: xenial
services:
  - docker
 
notifications:
  email:
    recipients:
      - ibai@erlerobotics.com
    on_failure: always

before_script:
  - mkdir /tmp/hrim
  - mv * /tmp/hrim
  - cd .docker/ci

script:
  - docker build -t acutronicrobotics/hrim .
  - docker run -v /tmp/hrim:/home/root/ros2_ws/src/hrim acutronicrobotics/hrim
